const UPDATE_APPLIANCE = "UPDATE_APPLIANCE";
const UPDATE_AMOUNT_APPLIANCE = "UPDATE_AMOUNT_APPLIANCE";
const UPDATE_COMERCIAL = "UPDATE_COMERCIAL";
const UPDATE_GENERAL = "UPDATE_GENERAL";
const UPDATE_DOCUMENTS = "UPDATE_DOCUMENTS";