export const UPDATE_NAVBAR = "UPDATE_NAVBAR";
export const UPDATE_DATE = "UPDATE_DATE";
export const UPDATE_DROPDOWN = "UPDATE_DROPDOWN";
export const UPDATE_TOAST = "UPDATE_TOAST";
export const UPDATE_TOAST_REGISTER = "UPDATE_TOAST_REGISTER";