export const UPADATE_BURO = "UPADATE_BURO";
export const UPDATE_BURO_SCORE = "UPDATE_BURO_SCORE";
export const UPDATE_BURO_MORAL = "UPDATE_BURO_MORAL";
export const UPDATE_BURO_MORAL_SCORE = "UPDATE_BURO_MORAL_SCORE";