export const UPDATE_DOCUMENTS_STATUS_COMPLETED = "UPDATE_DOCUMENTS_STATUS_COMPLETED";
export const UPDATE_NAME_DOCUMENTS_COMPLETED = "UPDATE_NAME_DOCUMENTS_COMPLETED";
export const UPDATE_TYPE_DOCUMENT = "UPDATE_TYPE_DOCUMENT";